'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './all-components/NavBar'
import AuthProvider from '../components/Authprovider/Authprovider'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react';
import store, { persistor } from '../app/redux/store'
import { usePathname } from 'next/navigation';
import Navbar2 from './all-components/NavBar2/Navbar2'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  const isHomePage = pathname === '/';
  

  return (
    <html lang="en">

      <body className=''>

        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <AuthProvider>
              <NavBar showSearchBar={!isHomePage}  />
              <Navbar2/>
              {children}
            </AuthProvider>
          </PersistGate>
        </Provider>
      </body>

    </html>
  )
}
